version: "3"
services:
  db:
    image: "postgres:11"
    container_name: ewallet-api-postgres
    ports:
      - "5432:5432"
    volumes:
      - my_dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_HOST=db
      - POSTGRES_DB=postgres
  api:
    image: "by.kliasheu/ewallet-api:latest"
    container_name: ewallet-api
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=postgres
      - POSTGRES_HOST=db

    depends_on:
      - db
    links:
      - db
volumes:
  my_dbdata:
